# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/go-delve/delve/releases/download/v1.26.3/dlv_1.26.3_darwin_arm64.tar.gz";
      sha256 = "sha256-fyhIOkLwqRHymyNqpA0k1wmfGw7FTFbE1DmmkD1Hij0=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir && find $tmpdir -type f \( -name dlv \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for delve");
in
stdenv.mkDerivation rec {
  pname = "delve";
  version = "1.26.3";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/dlv
  '';
}
