# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/argoproj/argo-cd/releases/download/v3.4.1/argocd-darwin-arm64";
      sha256 = "sha256-Jqo566wiCpWU5qcqCXffTBTVH8Pc+J8hYkzbBY14a04=";
      extract = ''cp $src $out/bin/argocd'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for argo-cd");
in
stdenv.mkDerivation rec {
  pname = "argo-cd";
  version = "3.4.1";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/argocd
  '';
}
