# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://get.helm.sh/helm-v4.1.4-darwin-arm64.tar.gz";
      sha256 = "sha256-fC7KZ46AAfqGPN+Mv2rBs3mflASonrVcCCYO9XMuZY0=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir --strip-components=1 && find $tmpdir -type f \( -name helm \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for helm");
in
stdenv.mkDerivation rec {
  pname = "helm";
  version = "4.1.4";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/helm
  '';
}
