# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/bufbuild/buf/releases/download/v1.69.0/buf-Darwin-arm64.tar.gz";
      sha256 = "sha256-JGU0Z0I58ybdGtJkLleGXdVtxOmMSFfRPabspNOhaK0=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir --strip-components=2 && find $tmpdir -type f \( -name buf \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for buf");
in
stdenv.mkDerivation rec {
  pname = "buf";
  version = "1.69.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/buf
  '';
}
