shell = "zsh"
apply = ["defer"]

[templates]
defer = ""

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.async]
local = "~/workspace/sivchari/dotfiles/zsh"
use = ["{!sync,*}.zsh"]

[plugins.sync]
local = "~/workspace/sivchari/dotfiles/zsh"
use = ["sync.zsh"]
apply = ["source"]

