shell = "zsh"
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.sync]
local = "~/workspace/sivchari/dotfiles/zsh"
use = ["sync.zsh"]
apply = ["source"]

[plugins.kubectl-completion]
remote = "https://raw.githubusercontent.com/nnao45/zsh-kubectl-completion/master/_kubectl"
apply = ["fpath"]

