# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.13.1/clusterctl-darwin-arm64";
      sha256 = "sha256-+JzgMxiDkqRwgE7s7vcmxNLehuNhLF9sV381IO1Vymg=";
      extract = ''cp $src $out/bin/clusterctl'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for cluster-api");
in
stdenv.mkDerivation rec {
  pname = "cluster-api";
  version = "1.13.1";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/clusterctl
  '';
}
