# Code generated by dendrite; DO NOT EDIT.
{
  lib,
  stdenv,
  fetchurl,
  unzip,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://releases.hashicorp.com/terraform/1.15.2/terraform_1.15.2_darwin_arm64.zip";
      sha256 = "sha256-QgS8NFBBinzkI+WEUbBT5drtYlrWxqFd6YvAk0Umn5k=";
      extract = ''tmpdir=$(mktemp -d) && unzip -o $src -d $tmpdir && find $tmpdir -type f \( -name terraform \) -exec cp {} $out/bin/ \;'';
      needsUnzip = true;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for terraform");
in
stdenv.mkDerivation rec {
  pname = "terraform";
  version = "1.15.2";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;


  nativeBuildInputs = lib.optionals (platformSrc.needsUnzip or false) [ unzip ];


  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/terraform
  '';
}
