#!/bin/bash

# JankyBorders - Window border configuration
# https://github.com/FelixKratz/JankyBorders

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=0xffe1e3e4
  inactive_color=0xff494d64
)

borders "${options[@]}"
