# Code generated by dendrite; DO NOT EDIT.
{
  lib,
  stdenv,
  fetchurl,
  unzip,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/k1LoW/mo/releases/download/v1.6.8/mo_v1.6.8_darwin_arm64.zip";
      sha256 = "sha256-I0/CZUCZRKRrkOY6tIkXtHKhOQuDhkWTtYf0z2NqUjg=";
      extract = ''tmpdir=$(mktemp -d) && unzip -o $src -d $tmpdir && find $tmpdir -type f \( -name mo \) -exec cp {} $out/bin/ \;'';
      needsUnzip = true;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for mo");
in
stdenv.mkDerivation rec {
  pname = "mo";
  version = "1.6.8";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;


  nativeBuildInputs = lib.optionals (platformSrc.needsUnzip or false) [ unzip ];


  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/mo
  '';
}
