# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v4.14.0/kubebuilder_darwin_arm64";
      sha256 = "sha256-DB6yrBP0nkI5LgOSSlHY94ARCHSqUSvRKD8Gj/GvPEE=";
      extract = ''cp $src $out/bin/kubebuilder'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for kubebuilder");
in
stdenv.mkDerivation rec {
  pname = "kubebuilder";
  version = "4.14.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/kubebuilder
  '';
}
