# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/kubernetes-sigs/kind/releases/download/v0.31.0/kind-darwin-arm64";
      sha256 = "sha256-iL9VT+naYxHJ+MLQgmE8ACkRpHb2tQkOlCCzXYTnDFw=";
      extract = ''cp $src $out/bin/kind'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for kind");
in
stdenv.mkDerivation rec {
  pname = "kind";
  version = "0.31.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/kind
  '';
}
