# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/aquaproj/aqua/releases/download/v2.58.0/aqua_darwin_arm64.tar.gz";
      sha256 = "sha256-LWpdvfrBepyqJW+HEEuc5xbc1uuMvhwkittj0kEB2yE=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir && find $tmpdir -type f \( -name aqua \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for aqua");
in
stdenv.mkDerivation rec {
  pname = "aqua";
  version = "2.58.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/aqua
  '';
}
