# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/carapace-sh/carapace-bin/releases/download/v1.6.5/carapace-bin_1.6.5_darwin_arm64.tar.gz";
      sha256 = "sha256-lxXDwImOJbVE27h2jMZyf4L8nn0+81Il26qdY2NFKlM=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir && find $tmpdir -type f \( -name carapace \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for carapace-bin");
in
stdenv.mkDerivation rec {
  pname = "carapace-bin";
  version = "1.6.5";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/carapace
  '';
}
