# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://dl.k8s.io/release/v1.36.0/bin/darwin/arm64/kubectl";
      sha256 = "sha256-S88mjqzcHS33TjfYb2OfJ8p96jrhhbe0Urc7n7XdwU4=";
      extract = ''cp $src $out/bin/kubectl'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for kubectl");
in
stdenv.mkDerivation rec {
  pname = "kubectl";
  version = "1.36.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/kubectl
  '';
}
