# Code generated by dendrite; DO NOT EDIT.
{
  lib,
  stdenv,
  fetchurl,
  unzip,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/x-motemen/ghq/releases/download/v1.10.1/ghq_darwin_arm64.zip";
      sha256 = "sha256-XjEA3gxaJI7r5qsXatlNbhI4avcKWMU1NopDAYYbE5g=";
      extract = ''tmpdir=$(mktemp -d) && unzip -o $src -d $tmpdir && find $tmpdir -type f \( -name ghq \) -exec cp {} $out/bin/ \;'';
      needsUnzip = true;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for ghq");
in
stdenv.mkDerivation rec {
  pname = "ghq";
  version = "1.10.1";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;


  nativeBuildInputs = lib.optionals (platformSrc.needsUnzip or false) [ unzip ];


  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/ghq
  '';
}
