# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/charmbracelet/vhs/releases/download/v0.11.0/vhs_0.11.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-7ske5FC6ULbU/OKABZOyrF/diKcwVjZ9LDuHDuRN4/c=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir --strip-components=1 && find $tmpdir -type f \( -name vhs \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for vhs");
in
stdenv.mkDerivation rec {
  pname = "vhs";
  version = "0.11.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/vhs
  '';
}
