# Code generated by dendrite; DO NOT EDIT.
{
  lib,
  stdenv,
  fetchurl,
  unzip,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/protocolbuffers/protobuf/releases/download/v34.1/protoc-34.1-osx-aarch_64.zip";
      sha256 = "sha256-LH6SuLV4kWk33xMrMDLi6ObBcIYuz3qDMwlKbz0DZQw=";
      extract = ''tmpdir=$(mktemp -d) && unzip -o $src -d $tmpdir && find $tmpdir -type f \( -name protoc \) -exec cp {} $out/bin/ \;'';
      needsUnzip = true;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for protobuf");
in
stdenv.mkDerivation rec {
  pname = "protobuf";
  version = "34.1";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;


  nativeBuildInputs = lib.optionals (platformSrc.needsUnzip or false) [ unzip ];


  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/protoc
  '';
}
