# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/sivchari/gopls-lazy/releases/download/v0.4.1/gopls-lazy_0.4.1_darwin_arm64.tar.gz";
      sha256 = "sha256-KSW+vXA7AT7zwX2ZkHE8D3ex21YHe90ewL8sl/Wx4X8=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir && find $tmpdir -type f \( -name gopls-lazy \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for gopls-lazy");
in
stdenv.mkDerivation rec {
  pname = "gopls-lazy";
  version = "0.4.1";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/gopls-lazy
  '';
}
