# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/astral-sh/uv/releases/download/0.11.11/uv-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-Ohhb+PRqe3yLkQ0RGCWQexY40K5QPLPDM64gV3I1QEY=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir --strip-components=1 && find $tmpdir -type f \( -name uv -o -name uvx \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for uv");
in
stdenv.mkDerivation rec {
  pname = "uv";
  version = "0.11.11";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/uv
    chmod +x $out/bin/uvx
  '';
}
