# [[dein.toml]]
[[plugins]]
repo = 'Shougo/dein.vim'

# Theme
[[plugins]]
repo = 'wojciechkepka/vim-github-dark'
hook_add = '''
    colorscheme ghdark
'''

# Tree Plug
[[plugins]]
repo = 'lambdalisue/fern.vim'

# Git Status
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

# Font
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
    augroup my-glyph-palette
      autocmd! *
      autocmd FileType fern call glyph_palette#apply()
      autocmd FileType nerdtree,startify call glyph_palette#apply()
    augroup END
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_theme = "luna"
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Tab AutoComplete
[[plugins]]
repo = 'ervandew/supertab'

# Quick Run
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    set splitbelow
    set splitright
'''

# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim']
hook_add= '''
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'nim',
    \ 'whitelist': ['nim'],
    \ 'completor': {opt, ctx -> nim#suggest#sug#GetAllCandidates({start, candidates -> asyncomplete#complete(opt['name'], ctx, start, candidates)})}
    \ })
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add= '''
    let g:rustfmt_autosave = 1
'''

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'

# vim-go-expr
[[plugins]]
repo = '110y/vim-go-expr-completion'

# scala
[[plugins]]
repo = 'jparise/vim-graphql'

# vim-prettier
[[plugins]]
repo = 'prettier/vim-prettier'

# vim-delve
[[plugins]]
repo = 'sebdah/vim-delve'

# Markdown
[[plugins]]
repo = 'previm/previm'

# rainbow
[[plugins]]
repo = 'luochen1990/rainbow'

# tcomment_vim
# gcc > comment switch
# visual + gc > comment switch
[[plugins]]
repo = 'tomtom/tcomment_vim'

# win_resizer
[[plugins]]
repo = 'simeji/winresizer'

# easy motion
[[plugins]]
repo = 'easymotion/vim-easymotion'

# terminal on vim
[[plugins]]
repo = 'vimlab/split-term.vim'

# implements interface for Go
[[plugins]]
repo = 'mattn/vim-goimpl'
