# [[dein.toml]]
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wojciechkepka/vim-github-dark'
hook_add = '''
    colorscheme ghdark
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_powerline_fonts = 1
    let g:airline_theme = "luna"
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    set splitbelow
    set splitright
'''

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'alaviss/nim.nvim'
on_ft = ['nim']
hook_add= '''
au User asyncomplete_setup call asyncomplete#register_source({
    \ 'name': 'nim',
    \ 'whitelist': ['nim'],
    \ 'completor': {opt, ctx -> nim#suggest#sug#GetAllCandidates({start, candidates -> asyncomplete#complete(opt['name'], ctx, start, candidates)})}
    \ })
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add= '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'justmao945/vim-clang'
hook_add = '''
let g:clang_auto = 0
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_use_library = 1
let g:clang_c_completeopt   = 'menuone'
let g:clang_cpp_completeopt = 'menuone'
let g:clang_exec = 'clang'
let g:clang_format_exec = 'clang-format'
let g:clang_c_options = '-std=c11'
let g:clang_cpp_options = '-std=c++1z -stdlib=libc++ -pedantic-errors'
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

