# [[dein.toml]]
[[plugins]]
repo = 'Shougo/dein.vim'

# Tree Plug
[[plugins]]
repo = 'lambdalisue/fern.vim'

# Font
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

# Tab AutoComplete
[[plugins]]
repo = 'ervandew/supertab'

# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add= '''
    let g:rustfmt_autosave = 1
'''

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

# tcomment_vim
# gcc > comment switch
# visual + gc > comment switch
[[plugins]]
repo = 'tomtom/tcomment_vim'

# win_resizer
[[plugins]]
repo = 'simeji/winresizer'

# easy motion
[[plugins]]
repo = 'easymotion/vim-easymotion'

# terminal on vim
[[plugins]]
repo = 'vimlab/split-term.vim'

# implements interface for Go
[[plugins]]
repo = 'mattn/vim-goimpl'

