# Code generated by dendrite; DO NOT EDIT.
{
  lib,
  stdenv,
  fetchurl,
  unzip,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/cli/cli/releases/download/v2.92.0/gh_2.92.0_macOS_arm64.zip";
      sha256 = "sha256-sRxU9r19Fe1lkEdQeeWy/PNvRdOZGoAEGynJ0MwfHQc=";
      extract = ''tmpdir=$(mktemp -d) && unzip -o $src -d $tmpdir && find $tmpdir -type f \( -name gh \) -exec cp {} $out/bin/ \;'';
      needsUnzip = true;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for cli");
in
stdenv.mkDerivation rec {
  pname = "cli";
  version = "2.92.0";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;


  nativeBuildInputs = lib.optionals (platformSrc.needsUnzip or false) [ unzip ];


  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    chmod +x $out/bin/gh
  '';
}
