shell = "zsh"
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.carapace]
inline = '''
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
carapace_cache="${XDG_CACHE_HOME:-$HOME/.cache}/carapace.zsh"
if [[ ! -r "$carapace_cache" ]]; then
  carapace _carapace > "$carapace_cache"
fi
zsh-defer source "$carapace_cache"
unset carapace_cache
'''

[plugins.sync]
local = "~/.config/sheldon/zsh"
use = ["sync.zsh"]
apply = ["source"]


