# Code generated by dendrite; DO NOT EDIT.
{
  stdenv,
  fetchurl,
}:
let
  platform = stdenv.hostPlatform.system;
  sources = {
    "aarch64-darwin" = {
      url = "https://github.com/mikefarah/yq/releases/download/v4.53.2/yq_darwin_arm64.tar.gz";
      sha256 = "sha256-8TXAxg7dXe0RvEGNEnEcJZeVsXUBES6EPpPno5WaPUE=";
      extract = ''tmpdir=$(mktemp -d) && tar -xzf $src -C $tmpdir && find $tmpdir -type f \( -name yq_darwin_arm64 \) -exec cp {} $out/bin/ \;'';
      needsUnzip = false;
    };
  };
  platformSrc = sources.${platform} or (throw "dendrite: unsupported platform ${platform} for yq");
in
stdenv.mkDerivation rec {
  pname = "yq";
  version = "4.53.2";

  src = fetchurl { inherit (platformSrc) url sha256; };

  dontUnpack = true;
  dontStrip = true;



  installPhase = ''
    mkdir -p $out/bin
    ${platformSrc.extract}
    mv $out/bin/yq_darwin_arm64 $out/bin/yq
    chmod +x $out/bin/yq
  '';
}
